### ISSUE TITLE
Nozzle size dropdown is *still* empty

### ISSUE THREAD

**Issue by ilgrank** [speckone/cura_cr6se#2]
Hello!
Thanks for your work!

I've read on reddit you fixed it, but it I see still it this way.. anything I can try?
Thanks for your work!

**Comment by speckone** [comment]
I've only tested this with Cura 4.7.1

What version are you using?

**Comment by ilgrank** [comment]
I'm on 4.6.2 since I've read that 4.7.1 is buggy.
I've read here tho:
https://www.reddit.com/r/CR6/comments/je25cc/new_version_of_creality_slicer_on_their_website/
that Creality uploaded a new version of their slicer that includes a fixed profile.

**Comment by speckone** [comment]
I didn't like using Cura because I found it to be incredibly slow, so I've gone back to using Simplify3D. I've got a working profile for the CR6 in Simplify3D and it slices 10x faster than Cura(4.7.1).

**Comment by ilgrank** [comment]
Any chance you can update the profiles here for people still using Cura? Please :)
Btw, what do you mean by "It slices 10x faster"? Slicing a medium complexity project just takes a matter of seconds on my 10 year old i7 2600k anyways..

**Comment by ilgrank** [comment]
Nevermind, they have been included in Cura 4.8 beta, along with several fixes for creality printers.
Thanks anyway

**Comment by shinmai** [comment]
Any change of sharing your Simplify3D profiles for the CR6? I'm way more used to workign in S3D and would love to save the hassle of migrating stuff from Cura. Tried just whipping up my own from scratch, but got WAAAY worse results than from the custom 4.2 Cura Creality is distributing. (Also would _really_ like to avoid using a year-old version of Cura if S3D isn't a stress-free options :D)
